#pragma once

#include <cstdint>

constexpr int X_DISPLAY_RESOLUTION{800};
constexpr int Y_DISPLAY_RESOLUTION{600};
constexpr int X_INITIAL_WINDOW_POSITION{100};
constexpr int Y_INITIAL_WINDOW_POSITION{100};
constexpr int INPUT_SIGNAL_RESOLUTION{4096};
constexpr unsigned int DISPLAY_BUFFER_SIZE{X_DISPLAY_RESOLUTION};
constexpr uint8_t X_LENGTH{X_DISPLAY_RESOLUTION / DISPLAY_BUFFER_SIZE};
constexpr uint16_t FREQUENCY_LABEL_TIMEOUT_MS{500};
constexpr uint16_t DEFAULT_TRIGGER_THRESHOLD{(INPUT_SIGNAL_RESOLUTION / 2)};
constexpr uint16_t INVALID_VALUE{0xffff};